
version: '3'

services:
  mspostgres:
    image: postgres
    container_name: mspostgres
    environment:
      POSTGRES_PASSWORD: pass2022
    ports:
      - "15432:5432"
    volumes:
      - ./PostgreSQL:/var/lib/postgresql/data 
    extra_hosts:
      - docker.host.interntal:host-gateway
      
  mspgadmin:
    image: dpage/pgadmin4
    container_name: mspgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "user@email.com"
      PGADMIN_DEFAULT_PASSWORD: "PgAdmin2022!"
    ports:
      - "16543:80"
    depends_on:
      - mspostgres
    extra_hosts:
      - docker.host.interntal:host-gateway

  keycloak:
      image: quay.io/keycloak/keycloak
      container_name: keycloak
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: mspostgres
        DB_DATABASE: keycloak
        DB_USER: postgres
        DB_SCHEMA: public
        DB_PASSWORD: pass2022
        KEYCLOAK_USER: root
        KEYCLOAK_PASSWORD: Pa55w0rd
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 8080:8080
      depends_on:
        - mspostgres
      extra_hosts:
      - docker.host.interntal:host-gateway

networks:
  default:
    name: ms-network