name: myseries-api-ci
on:
  pull_request:
    branches:
      - dev
strategy:
  matrix:
    node: ['12', '14', '16']
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #coloca os arquivos que foram subidos em uma máquina ubuntu.
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm run test users/users.service.spec.ts
