name: myseries-api-ci
on:
  pull_request:
    branches:
      - dev

jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14', '16']
    steps:
      - uses: actions/checkout@v2 #coloca os arquivos que foram subidos em uma máquina ubuntu.
      - uses: actions/setup-node@v2
        with:
          node-version: ${{matrix.node}}
      - run: npm install
      - run: npm run test users/users.service.spec.ts

  docker-build-push-prod:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: philippeberto/myseries-api:latest
        secrets: |
            KEYCLOAK_PUBLIC_KEY=${{ secrets.MYTOKEN }}
            POSTGRE_URL_CONNECTION_PROD=${{ secrets.POSTGRE_URL_CONNECTION_PROD }}
            POSTGRE_URL_CONNECTION=${{ secrets.POSTGRE_URL_CONNECTION }}
            BASE_KEYCLOAK_URL=${{ secrets.BASE_KEYCLOAK_URL }}
            KEYCLOAK_CLIENT_ID=${{ secrets.KEYCLOAK_CLIENT_ID }}
            KEYCLOAK_CLIENT_SECRET=${{ secrets.KEYCLOAK_CLIENT_SECRET }}